package one.taya.fabrigradle;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;

import org.gradle.api.DefaultTask;
import org.gradle.api.tasks.OutputFile;
import org.gradle.api.tasks.TaskAction;

public class AcceptEulaTask extends DefaultTask {

    @OutputFile
    public File getOutputFile() {
        File folder = getProject().file("run");
        folder.mkdirs();
        return new File(folder, "eula.txt");
    }

    @TaskAction
    public void acceptEula() throws IOException {
        Files.writeString(getOutputFile().toPath(), """
        #File generated by Fabrigradle
        #By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
        eula=true
        """, StandardOpenOption.CREATE);
    }

}
